# Generated by Django 4.2.20 on 2025-05-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Image',
            new_name='ProjectImage',
        ),
        migrations.RenameModel(
            old_name='Project_Service',
            new_name='ProjectService',
        ),
        migrations.RenameModel(
            old_name='Project_Specifications',
            new_name='ProjectSpecifications',
        ),
        migrations.RemoveField(
            model_name='service',
            name='students',
        ),
        migrations.AddField(
            model_name='service',
            name='projects',
            field=models.ManyToManyField(help_text='Проекты, в которых доступна эта услуга', related_name='services', through='projects.ProjectService', to='projects.project', verbose_name='Связанные проекты'),
        ),
    ]
