# Generated by Django 4.2.20 on 2025-05-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_project_image_projectimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectservice',
            options={'verbose_name': 'Услуга в проекте', 'verbose_name_plural': 'Услуги в проекте'},
        ),
        migrations.AlterModelOptions(
            name='projectspecifications',
            options={'verbose_name': 'Характеристики проекта', 'verbose_name_plural': 'Характеристики проектов'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='count_services',
        ),
    ]
