# Generated by Django 4.2.20 on 2025-05-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_service_projects_project_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(help_text='Услуги которые были добавлены для этого проекта', related_name='projects', through='projects.ProjectService', to='projects.service', verbose_name='Услуги в проекте'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='area',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='construction_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='Стоимость строительства от'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='exterior_decoration',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Наружная отделка'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='floors',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этажность'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='foundation',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Фундамент'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='overall_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='overall_width',
            field=models.FloatField(blank=True, null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='overlap',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Перекрытие'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='roof_type',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Тип кровли'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='roofing_material',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Кровельный материал'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='wall_material',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Материал стен'),
        ),
    ]
