# Generated by Django 4.2.20 on 2025-06-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectspecifications',
            name='area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='projectspecifications',
            name='construction_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Стоимость строительства от'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Название услуги'),
        ),
    ]
