services:
  postgres:
    image: postgres:15-alpine
    container_name: example-db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # environment:
      # - POSTGRES_DB=postgres
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
    env_file:
      - ../.env

volumes:
  postgres_data: