# Generated by Django 4.2.20 on 2025-05-21 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_alter_projectservice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('session_key', models.CharField(max_length=128, verbose_name='Ключ сессии')),
                ('project_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectservice', verbose_name='Услуга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
                'indexes': [models.Index(fields=['user', 'session_key'], name='baskets_bas_user_id_87ff0b_idx'), models.Index(fields=['project_service'], name='baskets_bas_project_7de793_idx')],
                'unique_together': {('session_key', 'project_service'), ('user', 'project_service')},
            },
        ),
    ]
